# Generated by Django 3.2.25 on 2025-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Resume', max_length=100)),
                ('file', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
